services:
  patientor-frontend:
    image: patientor-frontend
    build: ./frontend
    container_name: patientor-frontend

  patientor-backend:
    image: patientor-backend
    build: ./backend
    environment:
      - NODE_ENV=production
    container_name: patientor-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - patientor-frontend
      - patientor-backend
