services:
  patientor-frontend:
    image: patientor-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: patientor-frontend-dev

  patientor-backend:
    image: patientor-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: patientor-backend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: patientor-reverse-proxy
    depends_on:
      - patientor-frontend
      - patientor-backend
